---
- name: download grafana
  command: wget https://dl.grafana.com/oss/release/grafana_9.1.7_amd64.deb

- name: install grafana
  command: wget dpkg -i grafana_9.1.7_amd64.deb

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

