---

- include_vars: /home/ea/eadipl/terra/group_vars/dbservers/vars.yml


- name: "add address"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: bind-address = {{ db02_ip_addr }}
- name: Update MySQL configuration with server id
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#[\s]server-id'
    line: server-id = 2

- name: "update log_bin"
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#[\s]log_bin'
    line: log_bin = /var/log/mysql/mysql-bin.log


- name: "restart MySQL"
  systemd:
    name: mysql
    state: restarted
    enabled: yes


- name: Create wordpress user SQL query
  command: mysql -u root -e "CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED WITH mysql_native_password BY 'wordpress';"

- name: Create wordpress database SQL query
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS wordpress;"

- name: Provide wordpress user with all privileges SQL query
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';"



- name: "change Master" 
  ansible.builtin.command: mysql -u root -e "CHANGE MASTER TO MASTER_HOST ='{{ db01_ip_addr }}', MASTER_USER ='replicator', MASTER_PASSWORD ='password', MASTER_LOG_FILE = '{{ hostvars['db01.eadipl.ru']['mysql_master_file'].stdout }}', MASTER_LOG_POS = {{ hostvars['db01.eadipl.ru']['mysql_master_position'].stdout }};"

- name: "stop Slave"
  ansible.builtin.command: mysql -u root -e "START SLAVE;"

